ovsdb_client "${node["sr-dnsproxy"].ovsdb_client}"
ovsdb_server "${node["sr-dnsproxy"].ovsdb_server}"
ovsdb_database "${node["sr-dnsproxy"].ovsdb_database}"
router_name "${node["sr-dnsproxy"].router_name}"
max_queries ${node["sr-dnsproxy"].max_queries}
proxy_listen_port "${node["sr-dnsproxy"].proxy_listen_port}"
dns_server_port "${node["sr-dnsproxy"].dns_server_port}"
dns_server "${node["sr-dnsproxy"].dns_server}"
ntransacts ${node["sr-dnsproxy"].ntransacts}
