logfile ${node["sr-routed"].logfile}
pidfile ${node["sr-routed"].pidfile}
ovsdb_client ${node["sr-routed"].ovsdb_client}
ovsdb_server ${node["sr-routed"].ovsdb_server}
ovsdb_database ${node["sr-routed"].ovsdb_database}
dns_fifo ${node["sr-routed"].dns_fifo}
iproute ${node["sr-routed"].iproute}
vnhpref ${node["sr-routed"].vnhpref}
ingress_iface ${node["sr-routed"].ingress_iface}
